module.exports = {
	env: {
		node: true,
	},
	rules: {
		'getter-return': 'error',
		'no-compare-neg-zero': 'error',
		'no-cond-assign': ['error', 'except-parens'],
		'no-console': 'warn',
		'no-constant-condition': ['error', { 'checkLoops': false }],
		'no-control-regex': 'error',
		'no-debugger': 'error',
		'no-dupe-args': 'error',
		'no-dupe-keys': 'error',
		'no-duplicate-case': 'error',
		'no-empty': 'error',
		'no-empty-character-class': 'error',
		'no-ex-assign': 'error',
		'no-extra-boolean-cast': 'error',
		'no-extra-parens': ['error', 'all', {
			'returnAssign': false,
			'nestedBinaryExpressions': false,
			'enforceForArrowConditionals': false,
		}],
		'no-extra-semi': 'error',
		'no-func-assign': 'error',
		'no-inner-declarations': 'error',
		'no-invalid-regexp': 'error',
		'no-irregular-whitespace': ['error', { 'skipTemplates': true }],
		'no-obj-calls': 'error',
		'no-sparse-arrays': 'error',
		'no-template-curly-in-string': 'warn',
		'no-unexpected-multiline': 'error',
		'no-unreachable': 'error',
		'no-unsafe-finally': 'error',
		'no-unsafe-negation': 'error',
		'use-isnan': 'error',
		'valid-jsdoc': ['warn', {
			'requireReturn': false,
			'prefer': {
				'arg': 'param',
				'argument': 'param',
				'constructor': 'class',
				'return': 'returns',
				'virtual': 'abstract',
			},
			'preferType': {
				'Boolean': 'boolean',
				'Number': 'number',
				'object': 'Object',
				'String': 'string',
			},
		}],
		'array-callback-return': 'error',
		'complexity': 'warn',
		'consistent-return': 'error',
		'curly': ['error', 'all'],
		'default-case': 'error',
		'dot-location': ['error', 'property'],
		'dot-notation': ['error', { 'allowPattern': '^[a-z]+(_[a-z]+)+$' }],
		'eqeqeq': ['error', 'smart'],
		'no-alert': 'error',
		'no-caller': 'error',
		'no-case-declarations': 'error',
		'no-else-return': 'error',
		'no-empty-function': 'error',
		'no-empty-pattern': 'error',
		'no-eval': 'error',
		'no-extend-native': 'error',
		'no-extra-bind': 'error',
		'no-extra-label': 'error',
		'no-floating-decimal': 'error',
		'no-global-assign': 'error',
		'no-implicit-coercion': ['error', { 'allow': ['!!'] }],
		'no-implied-eval': 'error',
		'no-invalid-this': 'error',
		'no-lone-blocks': 'error',
		'no-multi-spaces': 'error',
		'no-multi-str': 'error',
		'no-new': 'error',
		'no-new-func': 'error',
		'no-new-wrappers': 'error',
		'no-octal': 'error',
		'no-octal-escape': 'error',
		'no-proto': 'error',
		'no-redeclare': 'error',
		'no-return-await': 'error',
		'no-self-assign': 'error',
		'no-self-compare': 'warn',
		'no-sequences': 'error',
		'no-throw-literal': 'error',
		'no-unmodified-loop-condition': 'error',
		'no-unused-expressions': 'warn',
		'no-unused-labels': 'error',
		'no-useless-call': 'error',
		'no-useless-concat': 'error',
		'no-useless-escape': 'error',
		'no-useless-return': 'error',
		'no-void': 'error',
		'no-with': 'error',
		'prefer-promise-reject-errors': 'error',
		'radix': 'error',
		'require-await': 'error',
		'wrap-iife': 'error',
		'yoda': 'error',
		'init-declarations': 'warn',
		'no-label-var': 'error',
		'no-shadow': ['error', { 'allow': ['_'] }],
		'no-undef': 'error',
		'no-undef-init': 'error',
		'no-undefined': 'error',
		'no-unused-vars': 'error',
		'no-use-before-define': 'error',
		'callback-return': 'warn',
		'handle-callback-err': 'error',
		'no-buffer-constructor': 'error',
		'no-mixed-requires': 'error',
		'no-path-concat': 'error',
		'array-bracket-spacing': ['error', 'never', {
			'objectsInArrays': true,
			'arraysInArrays': true,
		}],
		'block-spacing': 'error',
		'brace-style': ['error', '1tbs', { 'allowSingleLine': true }],
		'camelcase': 'error',
		'comma-dangle': ['error', 'always-multiline'],
		'comma-spacing': ['error', { 'before': false, 'after': true }],
		'comma-style': ['error', 'last'],
		'computed-property-spacing': ['error', 'never'],
		'eol-last': ['error', 'always'],
		'func-call-spacing': 'error',
		'func-names': 'warn',
		'indent': ['error', 'tab'],
		'key-spacing': ['error', {
			'beforeColon': false,
			'afterColon': true,
			'mode': 'strict',
		}],
		'keyword-spacing': 'error',
		'linebreak-style': 'error',
		'max-depth': ['warn', 6],
		'max-len': ['warn', { 'code': 140 }],
		'max-nested-callbacks': 'warn',
		'max-statements-per-line': 'error',
		'no-array-constructor': 'error',
		'no-bitwise': 'error',
		'no-lonely-if': 'error',
		'no-mixed-operators': 'error',
		'no-mixed-spaces-and-tabs': 'error',
		'no-multi-assign': 'error',
		'no-multiple-empty-lines': 'error',
		'no-nested-ternary': 'error',
		'no-plusplus': 'error',
		'no-new-object': 'error',
		'no-trailing-spaces': 'error',
		'no-unneeded-ternary': 'warn',
		'no-whitespace-before-property': 'error',
		'nonblock-statement-body-position': 'error',
		'object-curly-spacing': ['error', 'always'],
		'operator-assignment': 'warn',
		'quotes': ['error', 'single'],
		'semi': ['error', 'never'],
		'semi-spacing': ['error', { 'before': false, 'after': true }],
		'space-before-blocks': 'error',
		'space-before-function-paren': ['error', 'never'],
		'space-in-parens': 'error',
		'space-infix-ops': 'error',
		'space-unary-ops': 'error',
		'switch-colon-spacing': 'error',
		'template-tag-spacing': 'error',
		'arrow-body-style': 'error',
		'arrow-parens': ['error', 'as-needed'],
		'arrow-spacing': 'error',
		'constructor-super': 'error',
		'generator-star-spacing': 'error',
		'no-class-assign': 'error',
		'no-confusing-arrow': 'error',
		'no-const-assign': 'error',
		'no-dupe-class-members': 'error',
		'no-duplicate-imports': 'error',
		'no-new-symbol': 'error',
		'no-this-before-super': 'error',
		'no-useless-computed-key': 'error',
		'no-useless-constructor': 'error',
		'no-useless-rename': 'error',
		'no-var': 'error',
		'object-shorthand': 'warn',
		'prefer-const': 'error',
		'prefer-rest-params': 'error',
		'prefer-spread': 'error',
		'prefer-template': 'error',
		'require-yield': 'error',
		'rest-spread-spacing': 'error',
		'symbol-description': 'error',
		'template-curly-spacing': ['error', 'always'],
		'yield-star-spacing': 'error',
	},
}